name: Deploy to Hosting
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  # schedule:
  #   - cron: "0 1 * * 1,4,6"
  workflow_dispatch:
    inputs:
      Name:
        description: Main Deploy to Hosting
        required: true
        default: 'Main Deploy to Hosting'
jobs:
  deploy_136:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout Repository 136
        uses: actions/checkout@v4
      - name: Deploy to Hosting 136
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_136 }}
          username: ${{ secrets.FTP_USERNAME_136 }}
          password: ${{ secrets.FTP_PASSWORD_136 }}
          server-dir: ${{ secrets.FTP_DIR_136 }}
          local-dir: ./
          state-name: .status.json
          exclude: |
            **/.git/**
            **/.github/**
            **/src/**
            **/.gitattributes
            **/.gitignore
            **/bower.json
            **/food.sublime-project
            **/Gruntfile.js
            **/LICENSE
            **/README.md
            **/package.json
            **/bower_components/**
            **/node_modules/**
            **/test/**
            **/package-lock.json
      - name: Remove Status 136
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER_136 }}
          user: ${{ secrets.FTP_USERNAME_136 }}
          password: ${{ secrets.FTP_PASSWORD_136 }}
          remoteFiles: ".status.json"
          workingDir: ${{ secrets.FTP_DIR_136 }}
          ignoreSSL: 1
  deploy_294:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout Repository 294
        uses: actions/checkout@v4
      - name: Deploy to Hosting 294
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_294 }}
          username: ${{ secrets.FTP_USERNAME_294 }}
          password: ${{ secrets.FTP_PASSWORD_294 }}
          server-dir: ${{ secrets.FTP_DIR_294 }}
          local-dir: ./
          state-name: .status.json
          exclude: |
            **/.git/**
            **/.github/**
            **/src/**
            **/.gitattributes
            **/.gitignore
            **/bower.json
            **/food.sublime-project
            **/Gruntfile.js
            **/LICENSE
            **/README.md
            **/package.json
            **/bower_components/**
            **/node_modules/**
            **/test/**
            **/package-lock.json
      - name: Remove Status 294
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER_294 }}
          user: ${{ secrets.FTP_USERNAME_294 }}
          password: ${{ secrets.FTP_PASSWORD_294 }}
          remoteFiles: ".status.json"
          workingDir: ${{ secrets.FTP_DIR_294 }}
          ignoreSSL: 1
  deploy_469:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout Repository 469
        uses: actions/checkout@v4
      - name: Deploy to Hosting 469
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_469 }}
          username: ${{ secrets.FTP_USERNAME_469 }}
          password: ${{ secrets.FTP_PASSWORD_469 }}
          server-dir: ${{ secrets.FTP_DIR_469 }}
          local-dir: ./
          state-name: .status.json
          exclude: |
            **/.git/**
            **/.github/**
            **/src/**
            **/.gitattributes
            **/.gitignore
            **/bower.json
            **/food.sublime-project
            **/Gruntfile.js
            **/LICENSE
            **/README.md
            **/package.json
            **/bower_components/**
            **/node_modules/**
            **/test/**
            **/package-lock.json
      - name: Remove Status 469
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER_469 }}
          user: ${{ secrets.FTP_USERNAME_469 }}
          password: ${{ secrets.FTP_PASSWORD_469 }}
          remoteFiles: ".status.json"
          workingDir: ${{ secrets.FTP_DIR_469 }}
          ignoreSSL: 1
