name: Upload files to school hostings
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  schedule:
    - cron: "0 1 * * 1,4,6"
  workflow_dispatch:
    inputs:
      Name:
        description: Upload files to school hostings
        required: true
        default: 'Upload files to school hostings'
jobs:
  # Комсомольский
  komsomolskiy:
    name: Комсомольский
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
