name: Upload files to school hostings
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  schedule:
    - cron: "0 1 * * 1,4,6"
  workflow_dispatch:
    inputs:
      Name:
        description: Upload files to school hostings
        required: true
        default: 'Upload files to school hostings'
jobs:
  # Комсомольский
  komsomolskiy:
    name: Комсомольский
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Deploy to Hosting Комсомольский
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_136 }}
          username: ${{ secrets.FTP_USERNAME_136 }}
          password: ${{ secrets.FTP_PASSWORD_136 }}
          server-dir: ${{ secrets.FTP_DIR_136 }}
          local-dir: ./
          state-name: .status.json
          exclude: |
            **/.git/**
            **/.github/**
            **/src/**
            **/.gitattributes
            **/.gitignore
            **/bower.json
            **/food.sublime-project
            **/Gruntfile.js
            **/LICENSE
            **/README.md
            **/package.json
            **/bower_components/**
            **/node_modules/**
            **/test/**
            **/package-lock.json
      - name: Remove Status file Комсомольский
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER_136 }}
          user: ${{ secrets.FTP_USERNAME_136 }}
          password: ${{ secrets.FTP_PASSWORD_136 }}
          remoteFiles: ".status.json"
          workingDir: ${{ secrets.FTP_DIR_136 }}
          ignoreSSL: 1
  # Подбельск
  podbelsk:
    name: Подбельск
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Deploy to Hosting Подбельск
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_294 }}
          username: ${{ secrets.FTP_USERNAME_294 }}
          password: ${{ secrets.FTP_PASSWORD_294 }}
          server-dir: ${{ secrets.FTP_DIR_294 }}
          local-dir: ./
          state-name: .status.json
          exclude: |
            **/.git/**
            **/.github/**
            **/src/**
            **/.gitattributes
            **/.gitignore
            **/bower.json
            **/food.sublime-project
            **/Gruntfile.js
            **/LICENSE
            **/README.md
            **/package.json
            **/bower_components/**
            **/node_modules/**
            **/test/**
            **/package-lock.json
      - name: Remove Status file Подбельск
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER_294 }}
          user: ${{ secrets.FTP_USERNAME_294 }}
          password: ${{ secrets.FTP_PASSWORD_294 }}
          remoteFiles: ".status.json"
          workingDir: ${{ secrets.FTP_DIR_294 }}
          ignoreSSL: 1
  # Парфёновка
  parfenovka:
    name: Парфёновка
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Deploy to Hosting Парфёновка
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_469 }}
          username: ${{ secrets.FTP_USERNAME_469 }}
          password: ${{ secrets.FTP_PASSWORD_469 }}
          server-dir: ${{ secrets.FTP_DIR_469 }}
          local-dir: ./
          state-name: .status.json
          exclude: |
            **/.git/**
            **/.github/**
            **/src/**
            **/.gitattributes
            **/.gitignore
            **/bower.json
            **/food.sublime-project
            **/Gruntfile.js
            **/LICENSE
            **/README.md
            **/package.json
            **/bower_components/**
            **/node_modules/**
            **/test/**
            **/package-lock.json
      - name: Remove Status file Парфёновка
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER_469 }}
          user: ${{ secrets.FTP_USERNAME_469 }}
          password: ${{ secrets.FTP_PASSWORD_469 }}
          remoteFiles: ".status.json"
          workingDir: ${{ secrets.FTP_DIR_469 }}
          ignoreSSL: 1
  # Бобровка
  #bobrovka:
  #  name: Бобровка
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      node: [20]
  #  steps:
  #    - name: Checkout Repository
  #      uses: actions/checkout@v4
  #    - name: Deploy to Hosting Бобровка
  #      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
  #      with:
  #        server: ${{ secrets.FTP_SERVER_852 }}
  #        username: ${{ secrets.FTP_USERNAME_852 }}
  #        password: ${{ secrets.FTP_PASSWORD_852 }}
  #        server-dir: ${{ secrets.FTP_DIR_852 }}
  #        local-dir: ./
  #        state-name: .status.json
  #        exclude: |
  #          **/.git/**
  #          **/.github/**
  #          **/src/**
  #          **/.gitattributes
  #          **/.gitignore
  #          **/bower.json
  #          **/food.sublime-project
  #          **/Gruntfile.js
  #          **/LICENSE
  #          **/README.md
  #          **/package.json
  #          **/bower_components/**
  #          **/node_modules/**
  #          **/test/**
  #          **/package-lock.json
  #    - name: Remove Status file Бобровка
  #      uses: StephanThierry/ftp-delete-action@v2.1
  #      with:
  #        host: ${{ secrets.FTP_SERVER_852 }}
  #        user: ${{ secrets.FTP_USERNAME_852 }}
  #        password: ${{ secrets.FTP_PASSWORD_852 }}
  #        remoteFiles: ".status.json"
  #        workingDir: ${{ secrets.FTP_DIR_852 }}
  #        ignoreSSL: 1
  # Бобровка СП ДС
  #bobrovka_spds:
  #  name: Бобровка СП ДС
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      node: [20]
  #  steps:
  #    - name: Checkout Repository
  #      uses: actions/checkout@v4
  #    - name: Deploy to Hosting Бобровка
  #      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
  #      with:
  #        server: ${{ secrets.FTP_SERVER_8817 }}
  #        username: ${{ secrets.FTP_USERNAME_8817 }}
  #        password: ${{ secrets.FTP_PASSWORD_8817 }}
  #        server-dir: ${{ secrets.FTP_DIR_8817 }}
  #        local-dir: ./
  #        state-name: .status.json
  #        exclude: |
  #          **/.git/**
  #          **/.github/**
  #          **/src/**
  #          **/.gitattributes
  #          **/.gitignore
  #          **/bower.json
  #          **/food.sublime-project
  #          **/Gruntfile.js
  #          **/LICENSE
  #          **/README.md
  #          **/package.json
  #          **/bower_components/**
  #          **/node_modules/**
  #          **/test/**
  #          **/package-lock.json
  #    - name: Remove Status file Бобровка СП ДС
  #      uses: StephanThierry/ftp-delete-action@v2.1
  #      with:
  #        host: ${{ secrets.FTP_SERVER_8817 }}
  #        user: ${{ secrets.FTP_USERNAME_8817 }}
  #        password: ${{ secrets.FTP_PASSWORD_8817 }}
  #        remoteFiles: ".status.json"
  #        workingDir: ${{ secrets.FTP_DIR_8817 }}
  #        ignoreSSL: 1
  # Большая Малышевка
  bmalysh:
    name: Большая Малышевка
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Deploy to Hosting Бобровка
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_9022 }}
          username: ${{ secrets.FTP_USERNAME_9022 }}
          password: ${{ secrets.FTP_PASSWORD_9022 }}
          server-dir: ${{ secrets.FTP_DIR_9022 }}
          local-dir: ./
          state-name: .status.json
          exclude: |
            **/.git/**
            **/.github/**
            **/src/**
            **/.gitattributes
            **/.gitignore
            **/bower.json
            **/food.sublime-project
            **/Gruntfile.js
            **/LICENSE
            **/README.md
            **/package.json
            **/bower_components/**
            **/node_modules/**
            **/test/**
            **/package-lock.json
      - name: Remove Status file Бобровка СП ДС
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER_8817 }}
          user: ${{ secrets.FTP_USERNAME_8817 }}
          password: ${{ secrets.FTP_PASSWORD_8817 }}
          remoteFiles: ".status.json"
          workingDir: ${{ secrets.FTP_DIR_8817 }}
          ignoreSSL: 1
  # Большая Малышевка СП
  bmalysh_spds:
    name: Большая Малышевка СП ДС
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Deploy to Hosting Бобровка
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_9023 }}
          username: ${{ secrets.FTP_USERNAME_9023 }}
          password: ${{ secrets.FTP_PASSWORD_9023 }}
          server-dir: ${{ secrets.FTP_DIR_9023 }}
          local-dir: ./
          state-name: .status.json
          exclude: |
            **/.git/**
            **/.github/**
            **/src/**
            **/.gitattributes
            **/.gitignore
            **/bower.json
            **/food.sublime-project
            **/Gruntfile.js
            **/LICENSE
            **/README.md
            **/package.json
            **/bower_components/**
            **/node_modules/**
            **/test/**
            **/package-lock.json
      - name: Remove Status file Бобровка СП ДС
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER_8817 }}
          user: ${{ secrets.FTP_USERNAME_8817 }}
          password: ${{ secrets.FTP_PASSWORD_8817 }}
          remoteFiles: ".status.json"
          workingDir: ${{ secrets.FTP_DIR_8817 }}
          ignoreSSL: 1
